
default_registry(
   'docker.io/nezs',
)

sync_operator = sync('./src/operator.py', '/app/src/operator.py')
sync_utils = sync('./src/utils', '/app/src/utils')

docker_build('loki-op', '.',
    live_update=[
           sync_operator,
           sync_utils,
    ]

)

allow_k8s_contexts('production')
k8s_yaml('../manifestos/clusterrole-operator.yaml')
k8s_yaml('../manifestos/serviceaccount-operator.yaml')
k8s_yaml('../manifestos/clusterrolebinding-operator.yaml')
k8s_yaml('../manifestos/deployment-operator.yaml')
