apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: loki-operator-clusterrole
  namespace: api
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - '*'
- apiGroups:
    - ""
    - "apps"
  resources:
    - "configmaps"
    - "statefulsets"
    - "pods"
    - "namespaces"
    - "events"
  verbs:
    - "get"
    - "create"
    - "update"
    - "delete"
    - "list"
    - "watch"
    - "patch"
- apiGroups:
    - "jack.experts"
  resources:
    - "lokis"
    - "logalerts"
  verbs:
    - "*"
- apiGroups:
    - "admissionregistration.k8s.io"
    - "admissionregistration.k8s.io/v1beta1"
  resources:
    - "mutatingwebhookconfigurations"
    - "validatingwebhookconfigurations"
  verbs:
    - "create"
    - "patch"